package differ

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/Santiago1809/envforge/internal/parser"
)

type SyncOptions struct {
	SourcePath string
	TargetPath string
	Yes        bool
}

func Sync(opts *SyncOptions) error {
	sourceEnv, err := parser.Load(opts.SourcePath)
	if err != nil {
		return fmt.Errorf("failed to load source file %s: %w", opts.SourcePath, err)
	}

	targetPath := opts.TargetPath
	if targetPath == "" {
		targetPath = opts.SourcePath + ".example"
	}

	var targetEnv *parser.EnvFile
	if _, err := os.Stat(targetPath); err == nil {
		targetEnv, err = parser.Load(targetPath)
		if err != nil {
			return fmt.Errorf("failed to load target file %s: %w", targetPath, err)
		}
	} else {
		targetEnv = parser.NewEnvFile()
	}

	sourceKeys := sourceEnv.Keys()
	var newKeys []string

	for _, key := range sourceKeys {
		if _, exists := targetEnv.Get(key); !exists {
			targetEnv.Set(key, "")
			newKeys = append(newKeys, key)
		}
	}

	if !opts.Yes {
		fmt.Printf("Syncing %s → %s\n", opts.SourcePath, targetPath)
		if len(newKeys) > 0 {
			fmt.Println("New keys to add:")
			for _, k := range newKeys {
				fmt.Printf("  + %s\n", k)
			}
		} else {
			fmt.Println("No new keys to add.")
		}
		fmt.Print("Continue? [y/N]: ")

		scanner := bufio.NewScanner(os.Stdin)
		if !scanner.Scan() {
			return fmt.Errorf("aborted")
		}
		response := strings.ToLower(strings.TrimSpace(scanner.Text()))
		if response != "y" && response != "yes" {
			fmt.Println("Aborted.")
			return nil
		}
	}

	targetOrder := targetEnv.Keys()
	for _, key := range sourceKeys {
		if idx := indexOf(targetOrder, key); idx == -1 {
			targetOrder = append(targetOrder, key)
		}
	}

	finalEnv := parser.NewEnvFile()
	for _, key := range targetOrder {
		if val, exists := targetEnv.Get(key); exists {
			finalEnv.Set(key, val)
		} else {
			finalEnv.Set(key, "")
		}
	}

	err = finalEnv.Write(targetPath)
	if err != nil {
		return fmt.Errorf("failed to write target file %s: %w", targetPath, err)
	}

	if len(newKeys) > 0 {
		fmt.Printf("Successfully synced %d new key(s) to %s\n", len(newKeys), targetPath)
	} else {
		fmt.Printf("No new keys to sync. %s is up to date.\n", targetPath)
	}
	return nil
}

func indexOf(keys []string, key string) int {
	for i, k := range keys {
		if k == key {
			return i
		}
	}
	return -1
}

func SyncToExample(sourcePath string, yes bool) error {
	examplePath := sourcePath + ".example"

	sourceEnv, err := parser.Load(sourcePath)
	if err != nil {
		return fmt.Errorf("failed to load source file %s: %w", sourcePath, err)
	}

	var exampleEnv *parser.EnvFile
	if _, err := os.Stat(examplePath); err == nil {
		exampleEnv, err = parser.Load(examplePath)
		if err != nil {
			return fmt.Errorf("failed to load example file %s: %w", examplePath, err)
		}
	} else {
		exampleEnv = parser.NewEnvFile()
	}

	for _, key := range sourceEnv.Keys() {
		if _, exists := exampleEnv.Get(key); !exists {
			exampleEnv.Set(key, "")
		}
	}

	if !yes {
		fmt.Printf("Sync %s -> %s\n", sourcePath, examplePath)
		fmt.Println("This will add missing keys from .env to .env.example (values will be stripped).")
		fmt.Print("Continue? [y/N]: ")

		scanner := bufio.NewScanner(os.Stdin)
		if !scanner.Scan() {
			return fmt.Errorf("aborted")
		}
		response := strings.ToLower(strings.TrimSpace(scanner.Text()))
		if response != "y" && response != "yes" {
			fmt.Println("Aborted.")
			return nil
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by envoy sync\n")
	for _, key := range exampleEnv.Keys() {
		buf.WriteString(fmt.Sprintf("%s=\n", key))
	}

	err = os.WriteFile(examplePath, buf.Bytes(), 0644)
	if err != nil {
		return fmt.Errorf("failed to write example file: %w", err)
	}

	fmt.Printf("Successfully synced to %s\n", examplePath)
	return nil
}
