version: 2

project_name: envoy

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/envoy
    binary: envoy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

extra_files:
  - glob: ./dist/envoy_windows_amd64_v1/*.exe

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
