version: 2

project_name: envforge

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/envforge
    binary: envforge
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Santiago1809/envforge/cli.Version={{.Version}}
      - -X github.com/Santiago1809/envforge/cli.Commit={{.Commit}}
      - -X github.com/Santiago1809/envforge/cli.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
